package	TokenNamepackage
org	TokenNameIdentifier
.	TokenNameDOT
apache	TokenNameIdentifier
.	TokenNameDOT
batik	TokenNameIdentifier
.	TokenNameDOT
ext	TokenNameIdentifier
.	TokenNameDOT
swing	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
java	TokenNameIdentifier
.	TokenNameDOT
awt	TokenNameIdentifier
.	TokenNameDOT
BorderLayout	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
java	TokenNameIdentifier
.	TokenNameDOT
awt	TokenNameIdentifier
.	TokenNameDOT
Component	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
java	TokenNameIdentifier
.	TokenNameDOT
awt	TokenNameIdentifier
.	TokenNameDOT
Container	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
java	TokenNameIdentifier
.	TokenNameDOT
awt	TokenNameIdentifier
.	TokenNameDOT
FlowLayout	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
java	TokenNameIdentifier
.	TokenNameDOT
awt	TokenNameIdentifier
.	TokenNameDOT
Window	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
java	TokenNameIdentifier
.	TokenNameDOT
awt	TokenNameIdentifier
.	TokenNameDOT
event	TokenNameIdentifier
.	TokenNameDOT
ActionEvent	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
java	TokenNameIdentifier
.	TokenNameDOT
awt	TokenNameIdentifier
.	TokenNameDOT
event	TokenNameIdentifier
.	TokenNameDOT
ActionListener	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
java	TokenNameIdentifier
.	TokenNameDOT
awt	TokenNameIdentifier
.	TokenNameDOT
event	TokenNameIdentifier
.	TokenNameDOT
ComponentAdapter	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
java	TokenNameIdentifier
.	TokenNameDOT
awt	TokenNameIdentifier
.	TokenNameDOT
event	TokenNameIdentifier
.	TokenNameDOT
ComponentEvent	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
java	TokenNameIdentifier
.	TokenNameDOT
awt	TokenNameIdentifier
.	TokenNameDOT
event	TokenNameIdentifier
.	TokenNameDOT
KeyAdapter	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
java	TokenNameIdentifier
.	TokenNameDOT
awt	TokenNameIdentifier
.	TokenNameDOT
event	TokenNameIdentifier
.	TokenNameDOT
KeyEvent	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
java	TokenNameIdentifier
.	TokenNameDOT
awt	TokenNameIdentifier
.	TokenNameDOT
event	TokenNameIdentifier
.	TokenNameDOT
WindowAdapter	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
java	TokenNameIdentifier
.	TokenNameDOT
awt	TokenNameIdentifier
.	TokenNameDOT
event	TokenNameIdentifier
.	TokenNameDOT
WindowEvent	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
java	TokenNameIdentifier
.	TokenNameDOT
awt	TokenNameIdentifier
.	TokenNameDOT
geom	TokenNameIdentifier
.	TokenNameDOT
AffineTransform	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
java	TokenNameIdentifier
.	TokenNameDOT
io	TokenNameIdentifier
.	TokenNameDOT
Serializable	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
javax	TokenNameIdentifier
.	TokenNameDOT
swing	TokenNameIdentifier
.	TokenNameDOT
BorderFactory	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
javax	TokenNameIdentifier
.	TokenNameDOT
swing	TokenNameIdentifier
.	TokenNameDOT
JButton	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
javax	TokenNameIdentifier
.	TokenNameDOT
swing	TokenNameIdentifier
.	TokenNameDOT
JComponent	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
javax	TokenNameIdentifier
.	TokenNameDOT
swing	TokenNameIdentifier
.	TokenNameDOT
JDialog	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
javax	TokenNameIdentifier
.	TokenNameDOT
swing	TokenNameIdentifier
.	TokenNameDOT
JLabel	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
javax	TokenNameIdentifier
.	TokenNameDOT
swing	TokenNameIdentifier
.	TokenNameDOT
JOptionPane	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
javax	TokenNameIdentifier
.	TokenNameDOT
swing	TokenNameIdentifier
.	TokenNameDOT
JPanel	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
javax	TokenNameIdentifier
.	TokenNameDOT
swing	TokenNameIdentifier
.	TokenNameDOT
JTextField	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
javax	TokenNameIdentifier
.	TokenNameDOT
swing	TokenNameIdentifier
.	TokenNameDOT
border	TokenNameIdentifier
.	TokenNameDOT
Border	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
javax	TokenNameIdentifier
.	TokenNameDOT
swing	TokenNameIdentifier
.	TokenNameDOT
text	TokenNameIdentifier
.	TokenNameDOT
Document	TokenNameIdentifier
;	TokenNameSEMICOLON
public	TokenNamepublic
class	TokenNameclass
JAffineTransformChooser	TokenNameIdentifier
extends	TokenNameextends
JGridBagPanel	TokenNameIdentifier
{	TokenNameLBRACE
public	TokenNamepublic
static	TokenNamestatic
final	TokenNamefinal
String	TokenNameIdentifier
LABEL_ANGLE	TokenNameIdentifier
=	TokenNameEQUAL
"JAffineTransformChooser.label.angle"	TokenNameStringLiteral
;	TokenNameSEMICOLON
public	TokenNamepublic
static	TokenNamestatic
final	TokenNamefinal
String	TokenNameIdentifier
LABEL_DEGREE	TokenNameIdentifier
=	TokenNameEQUAL
"JAffineTransformChooser.label.degree"	TokenNameStringLiteral
;	TokenNameSEMICOLON
public	TokenNamepublic
static	TokenNamestatic
final	TokenNamefinal
String	TokenNameIdentifier
LABEL_PERCENT	TokenNameIdentifier
=	TokenNameEQUAL
"JAffineTransformChooser.label.percent"	TokenNameStringLiteral
;	TokenNameSEMICOLON
public	TokenNamepublic
static	TokenNamestatic
final	TokenNamefinal
String	TokenNameIdentifier
LABEL_ROTATE	TokenNameIdentifier
=	TokenNameEQUAL
"JAffineTransformChooser.label.rotate"	TokenNameStringLiteral
;	TokenNameSEMICOLON
public	TokenNamepublic
static	TokenNamestatic
final	TokenNamefinal
String	TokenNameIdentifier
LABEL_SCALE	TokenNameIdentifier
=	TokenNameEQUAL
"JAffineTransformChooser.label.scale"	TokenNameStringLiteral
;	TokenNameSEMICOLON
public	TokenNamepublic
static	TokenNamestatic
final	TokenNamefinal
String	TokenNameIdentifier
LABEL_RX	TokenNameIdentifier
=	TokenNameEQUAL
"JAffineTransformChooser.label.rx"	TokenNameStringLiteral
;	TokenNameSEMICOLON
public	TokenNamepublic
static	TokenNamestatic
final	TokenNamefinal
String	TokenNameIdentifier
LABEL_RY	TokenNameIdentifier
=	TokenNameEQUAL
"JAffineTransformChooser.label.ry"	TokenNameStringLiteral
;	TokenNameSEMICOLON
public	TokenNamepublic
static	TokenNamestatic
final	TokenNamefinal
String	TokenNameIdentifier
LABEL_SX	TokenNameIdentifier
=	TokenNameEQUAL
"JAffineTransformChooser.label.sx"	TokenNameStringLiteral
;	TokenNameSEMICOLON
public	TokenNamepublic
static	TokenNamestatic
final	TokenNamefinal
String	TokenNameIdentifier
LABEL_SY	TokenNameIdentifier
=	TokenNameEQUAL
"JAffineTransformChooser.label.sy"	TokenNameStringLiteral
;	TokenNameSEMICOLON
public	TokenNamepublic
static	TokenNamestatic
final	TokenNamefinal
String	TokenNameIdentifier
LABEL_TRANSLATE	TokenNameIdentifier
=	TokenNameEQUAL
"JAffineTransformChooser.label.translate"	TokenNameStringLiteral
;	TokenNameSEMICOLON
public	TokenNamepublic
static	TokenNamestatic
final	TokenNamefinal
String	TokenNameIdentifier
LABEL_TX	TokenNameIdentifier
=	TokenNameEQUAL
"JAffineTransformChooser.label.tx"	TokenNameStringLiteral
;	TokenNameSEMICOLON
public	TokenNamepublic
static	TokenNamestatic
final	TokenNamefinal
String	TokenNameIdentifier
LABEL_TY	TokenNameIdentifier
=	TokenNameEQUAL
"JAffineTransformChooser.label.ty"	TokenNameStringLiteral
;	TokenNameSEMICOLON
public	TokenNamepublic
static	TokenNamestatic
final	TokenNamefinal
String	TokenNameIdentifier
CONFIG_TEXT_FIELD_WIDTH	TokenNameIdentifier
=	TokenNameEQUAL
"JAffineTransformChooser.config.text.field.width"	TokenNameStringLiteral
;	TokenNameSEMICOLON
public	TokenNamepublic
static	TokenNamestatic
final	TokenNamefinal
String	TokenNameIdentifier
CONFIG_TOP_PAD	TokenNameIdentifier
=	TokenNameEQUAL
"JAffineTransformChooser.config.top.pad"	TokenNameStringLiteral
;	TokenNameSEMICOLON
public	TokenNamepublic
static	TokenNamestatic
final	TokenNamefinal
String	TokenNameIdentifier
CONFIG_LEFT_PAD	TokenNameIdentifier
=	TokenNameEQUAL
"JAffineTransformChooser.config.left.pad"	TokenNameStringLiteral
;	TokenNameSEMICOLON
public	TokenNamepublic
static	TokenNamestatic
final	TokenNamefinal
String	TokenNameIdentifier
CONFIG_BOTTOM_PAD	TokenNameIdentifier
=	TokenNameEQUAL
"JAffineTransformChooser.config.bottom.pad"	TokenNameStringLiteral
;	TokenNameSEMICOLON
public	TokenNamepublic
static	TokenNamestatic
final	TokenNamefinal
String	TokenNameIdentifier
CONFIG_RIGHT_PAD	TokenNameIdentifier
=	TokenNameEQUAL
"JAffineTransformChooser.config.right.pad"	TokenNameStringLiteral
;	TokenNameSEMICOLON
protected	TokenNameprotected
AffineTransform	TokenNameIdentifier
txf	TokenNameIdentifier
;	TokenNameSEMICOLON
protected	TokenNameprotected
DoubleDocument	TokenNameIdentifier
txModel	TokenNameIdentifier
=	TokenNameEQUAL
new	TokenNamenew
DoubleDocument	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
protected	TokenNameprotected
DoubleDocument	TokenNameIdentifier
tyModel	TokenNameIdentifier
=	TokenNameEQUAL
new	TokenNamenew
DoubleDocument	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
protected	TokenNameprotected
DoubleDocument	TokenNameIdentifier
sxModel	TokenNameIdentifier
=	TokenNameEQUAL
new	TokenNamenew
DoubleDocument	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
protected	TokenNameprotected
DoubleDocument	TokenNameIdentifier
syModel	TokenNameIdentifier
=	TokenNameEQUAL
new	TokenNamenew
DoubleDocument	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
protected	TokenNameprotected
DoubleDocument	TokenNameIdentifier
rxModel	TokenNameIdentifier
=	TokenNameEQUAL
new	TokenNamenew
DoubleDocument	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
protected	TokenNameprotected
DoubleDocument	TokenNameIdentifier
ryModel	TokenNameIdentifier
=	TokenNameEQUAL
new	TokenNamenew
DoubleDocument	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
protected	TokenNameprotected
DoubleDocument	TokenNameIdentifier
rotateModel	TokenNameIdentifier
=	TokenNameEQUAL
new	TokenNamenew
DoubleDocument	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
protected	TokenNameprotected
static	TokenNamestatic
final	TokenNamefinal
double	TokenNamedouble
RAD_TO_DEG	TokenNameIdentifier
=	TokenNameEQUAL
180.	TokenNameDoubleLiteral
/	TokenNameDIVIDE
Math	TokenNameIdentifier
.	TokenNameDOT
PI	TokenNameIdentifier
;	TokenNameSEMICOLON
protected	TokenNameprotected
static	TokenNamestatic
final	TokenNamefinal
double	TokenNamedouble
DEG_TO_RAD	TokenNameIdentifier
=	TokenNameEQUAL
Math	TokenNameIdentifier
.	TokenNameDOT
PI	TokenNameIdentifier
/	TokenNameDIVIDE
180.	TokenNameDoubleLiteral
;	TokenNameSEMICOLON
public	TokenNamepublic
JAffineTransformChooser	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
{	TokenNameLBRACE
build	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
setAffineTransform	TokenNameIdentifier
(	TokenNameLPAREN
new	TokenNamenew
AffineTransform	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
protected	TokenNameprotected
void	TokenNamevoid
build	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
{	TokenNameLBRACE
Component	TokenNameIdentifier
txyCmp	TokenNameIdentifier
=	TokenNameEQUAL
buildPanel	TokenNameIdentifier
(	TokenNameLPAREN
Resources	TokenNameIdentifier
.	TokenNameDOT
getString	TokenNameIdentifier
(	TokenNameLPAREN
LABEL_TRANSLATE	TokenNameIdentifier
)	TokenNameRPAREN
,	TokenNameCOMMA
Resources	TokenNameIdentifier
.	TokenNameDOT
getString	TokenNameIdentifier
(	TokenNameLPAREN
LABEL_TX	TokenNameIdentifier
)	TokenNameRPAREN
,	TokenNameCOMMA
txModel	TokenNameIdentifier
,	TokenNameCOMMA
Resources	TokenNameIdentifier
.	TokenNameDOT
getString	TokenNameIdentifier
(	TokenNameLPAREN
LABEL_TY	TokenNameIdentifier
)	TokenNameRPAREN
,	TokenNameCOMMA
tyModel	TokenNameIdentifier
,	TokenNameCOMMA
""	TokenNameStringLiteral
,	TokenNameCOMMA
""	TokenNameStringLiteral
,	TokenNameCOMMA
true	TokenNametrue
)	TokenNameRPAREN
;	TokenNameSEMICOLON
Component	TokenNameIdentifier
sxyCmp	TokenNameIdentifier
=	TokenNameEQUAL
buildPanel	TokenNameIdentifier
(	TokenNameLPAREN
Resources	TokenNameIdentifier
.	TokenNameDOT
getString	TokenNameIdentifier
(	TokenNameLPAREN
LABEL_SCALE	TokenNameIdentifier
)	TokenNameRPAREN
,	TokenNameCOMMA
Resources	TokenNameIdentifier
.	TokenNameDOT
getString	TokenNameIdentifier
(	TokenNameLPAREN
LABEL_SX	TokenNameIdentifier
)	TokenNameRPAREN
,	TokenNameCOMMA
sxModel	TokenNameIdentifier
,	TokenNameCOMMA
Resources	TokenNameIdentifier
.	TokenNameDOT
getString	TokenNameIdentifier
(	TokenNameLPAREN
LABEL_SY	TokenNameIdentifier
)	TokenNameRPAREN
,	TokenNameCOMMA
syModel	TokenNameIdentifier
,	TokenNameCOMMA
Resources	TokenNameIdentifier
.	TokenNameDOT
getString	TokenNameIdentifier
(	TokenNameLPAREN
LABEL_PERCENT	TokenNameIdentifier
)	TokenNameRPAREN
,	TokenNameCOMMA
Resources	TokenNameIdentifier
.	TokenNameDOT
getString	TokenNameIdentifier
(	TokenNameLPAREN
LABEL_PERCENT	TokenNameIdentifier
)	TokenNameRPAREN
,	TokenNameCOMMA
true	TokenNametrue
)	TokenNameRPAREN
;	TokenNameSEMICOLON
Component	TokenNameIdentifier
rCmp	TokenNameIdentifier
=	TokenNameEQUAL
buildRotatePanel	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
add	TokenNameIdentifier
(	TokenNameLPAREN
txyCmp	TokenNameIdentifier
,	TokenNameCOMMA
0	TokenNameIntegerLiteral
,	TokenNameCOMMA
0	TokenNameIntegerLiteral
,	TokenNameCOMMA
1	TokenNameIntegerLiteral
,	TokenNameCOMMA
1	TokenNameIntegerLiteral
,	TokenNameCOMMA
CENTER	TokenNameIdentifier
,	TokenNameCOMMA
BOTH	TokenNameIdentifier
,	TokenNameCOMMA
1	TokenNameIntegerLiteral
,	TokenNameCOMMA
1	TokenNameIntegerLiteral
)	TokenNameRPAREN
;	TokenNameSEMICOLON
add	TokenNameIdentifier
(	TokenNameLPAREN
sxyCmp	TokenNameIdentifier
,	TokenNameCOMMA
1	TokenNameIntegerLiteral
,	TokenNameCOMMA
0	TokenNameIntegerLiteral
,	TokenNameCOMMA
1	TokenNameIntegerLiteral
,	TokenNameCOMMA
1	TokenNameIntegerLiteral
,	TokenNameCOMMA
CENTER	TokenNameIdentifier
,	TokenNameCOMMA
BOTH	TokenNameIdentifier
,	TokenNameCOMMA
1	TokenNameIntegerLiteral
,	TokenNameCOMMA
1	TokenNameIntegerLiteral
)	TokenNameRPAREN
;	TokenNameSEMICOLON
add	TokenNameIdentifier
(	TokenNameLPAREN
rCmp	TokenNameIdentifier
,	TokenNameCOMMA
0	TokenNameIntegerLiteral
,	TokenNameCOMMA
1	TokenNameIntegerLiteral
,	TokenNameCOMMA
2	TokenNameIntegerLiteral
,	TokenNameCOMMA
1	TokenNameIntegerLiteral
,	TokenNameCOMMA
CENTER	TokenNameIdentifier
,	TokenNameCOMMA
BOTH	TokenNameIdentifier
,	TokenNameCOMMA
1	TokenNameIntegerLiteral
,	TokenNameCOMMA
1	TokenNameIntegerLiteral
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
protected	TokenNameprotected
Component	TokenNameIdentifier
buildRotatePanel	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
{	TokenNameLBRACE
JGridBagPanel	TokenNameIdentifier
panel	TokenNameIdentifier
=	TokenNameEQUAL
new	TokenNamenew
JGridBagPanel	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
Component	TokenNameIdentifier
anglePanel	TokenNameIdentifier
=	TokenNameEQUAL
buildPanel	TokenNameIdentifier
(	TokenNameLPAREN
Resources	TokenNameIdentifier
.	TokenNameDOT
getString	TokenNameIdentifier
(	TokenNameLPAREN
LABEL_ROTATE	TokenNameIdentifier
)	TokenNameRPAREN
,	TokenNameCOMMA
Resources	TokenNameIdentifier
.	TokenNameDOT
getString	TokenNameIdentifier
(	TokenNameLPAREN
LABEL_ANGLE	TokenNameIdentifier
)	TokenNameRPAREN
,	TokenNameCOMMA
rotateModel	TokenNameIdentifier
,	TokenNameCOMMA
null	TokenNamenull
,	TokenNameCOMMA
null	TokenNamenull
,	TokenNameCOMMA
Resources	TokenNameIdentifier
.	TokenNameDOT
getString	TokenNameIdentifier
(	TokenNameLPAREN
LABEL_DEGREE	TokenNameIdentifier
)	TokenNameRPAREN
,	TokenNameCOMMA
null	TokenNamenull
,	TokenNameCOMMA
false	TokenNamefalse
)	TokenNameRPAREN
;	TokenNameSEMICOLON
Component	TokenNameIdentifier
centerPanel	TokenNameIdentifier
=	TokenNameEQUAL
buildPanel	TokenNameIdentifier
(	TokenNameLPAREN
""	TokenNameStringLiteral
,	TokenNameCOMMA
Resources	TokenNameIdentifier
.	TokenNameDOT
getString	TokenNameIdentifier
(	TokenNameLPAREN
LABEL_RX	TokenNameIdentifier
)	TokenNameRPAREN
,	TokenNameCOMMA
rxModel	TokenNameIdentifier
,	TokenNameCOMMA
Resources	TokenNameIdentifier
.	TokenNameDOT
getString	TokenNameIdentifier
(	TokenNameLPAREN
LABEL_RY	TokenNameIdentifier
)	TokenNameRPAREN
,	TokenNameCOMMA
ryModel	TokenNameIdentifier
,	TokenNameCOMMA
null	TokenNamenull
,	TokenNameCOMMA
null	TokenNamenull
,	TokenNameCOMMA
false	TokenNamefalse
)	TokenNameRPAREN
;	TokenNameSEMICOLON
panel	TokenNameIdentifier
.	TokenNameDOT
add	TokenNameIdentifier
(	TokenNameLPAREN
anglePanel	TokenNameIdentifier
,	TokenNameCOMMA
0	TokenNameIntegerLiteral
,	TokenNameCOMMA
0	TokenNameIntegerLiteral
,	TokenNameCOMMA
1	TokenNameIntegerLiteral
,	TokenNameCOMMA
1	TokenNameIntegerLiteral
,	TokenNameCOMMA
CENTER	TokenNameIdentifier
,	TokenNameCOMMA
BOTH	TokenNameIdentifier
,	TokenNameCOMMA
1	TokenNameIntegerLiteral
,	TokenNameCOMMA
1	TokenNameIntegerLiteral
)	TokenNameRPAREN
;	TokenNameSEMICOLON
panel	TokenNameIdentifier
.	TokenNameDOT
add	TokenNameIdentifier
(	TokenNameLPAREN
centerPanel	TokenNameIdentifier
,	TokenNameCOMMA
1	TokenNameIntegerLiteral
,	TokenNameCOMMA
0	TokenNameIntegerLiteral
,	TokenNameCOMMA
1	TokenNameIntegerLiteral
,	TokenNameCOMMA
1	TokenNameIntegerLiteral
,	TokenNameCOMMA
CENTER	TokenNameIdentifier
,	TokenNameCOMMA
BOTH	TokenNameIdentifier
,	TokenNameCOMMA
1	TokenNameIntegerLiteral
,	TokenNameCOMMA
1	TokenNameIntegerLiteral
)	TokenNameRPAREN
;	TokenNameSEMICOLON
setPanelBorder	TokenNameIdentifier
(	TokenNameLPAREN
panel	TokenNameIdentifier
,	TokenNameCOMMA
Resources	TokenNameIdentifier
.	TokenNameDOT
getString	TokenNameIdentifier
(	TokenNameLPAREN
LABEL_ROTATE	TokenNameIdentifier
)	TokenNameRPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
return	TokenNamereturn
panel	TokenNameIdentifier
;	TokenNameSEMICOLON
}	TokenNameRBRACE
protected	TokenNameprotected
Component	TokenNameIdentifier
buildPanel	TokenNameIdentifier
(	TokenNameLPAREN
String	TokenNameIdentifier
panelName	TokenNameIdentifier
,	TokenNameCOMMA
String	TokenNameIdentifier
tfALabel	TokenNameIdentifier
,	TokenNameCOMMA
Document	TokenNameIdentifier
tfAModel	TokenNameIdentifier
,	TokenNameCOMMA
String	TokenNameIdentifier
tfBLabel	TokenNameIdentifier
,	TokenNameCOMMA
Document	TokenNameIdentifier
tfBModel	TokenNameIdentifier
,	TokenNameCOMMA
String	TokenNameIdentifier
tfASuffix	TokenNameIdentifier
,	TokenNameCOMMA
String	TokenNameIdentifier
tfBSuffix	TokenNameIdentifier
,	TokenNameCOMMA
boolean	TokenNameboolean
setBorder	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
JGridBagPanel	TokenNameIdentifier
panel	TokenNameIdentifier
=	TokenNameEQUAL
new	TokenNamenew
JGridBagPanel	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
addToPanelAtRow	TokenNameIdentifier
(	TokenNameLPAREN
tfALabel	TokenNameIdentifier
,	TokenNameCOMMA
tfAModel	TokenNameIdentifier
,	TokenNameCOMMA
tfASuffix	TokenNameIdentifier
,	TokenNameCOMMA
panel	TokenNameIdentifier
,	TokenNameCOMMA
0	TokenNameIntegerLiteral
)	TokenNameRPAREN
;	TokenNameSEMICOLON
if	TokenNameif
(	TokenNameLPAREN
tfBLabel	TokenNameIdentifier
!=	TokenNameNOT_EQUAL
null	TokenNamenull
)	TokenNameRPAREN
{	TokenNameLBRACE
addToPanelAtRow	TokenNameIdentifier
(	TokenNameLPAREN
tfBLabel	TokenNameIdentifier
,	TokenNameCOMMA
tfBModel	TokenNameIdentifier
,	TokenNameCOMMA
tfBSuffix	TokenNameIdentifier
,	TokenNameCOMMA
panel	TokenNameIdentifier
,	TokenNameCOMMA
1	TokenNameIntegerLiteral
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
if	TokenNameif
(	TokenNameLPAREN
setBorder	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
setPanelBorder	TokenNameIdentifier
(	TokenNameLPAREN
panel	TokenNameIdentifier
,	TokenNameCOMMA
panelName	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
return	TokenNamereturn
panel	TokenNameIdentifier
;	TokenNameSEMICOLON
}	TokenNameRBRACE
public	TokenNamepublic
void	TokenNamevoid
setPanelBorder	TokenNameIdentifier
(	TokenNameLPAREN
JComponent	TokenNameIdentifier
panel	TokenNameIdentifier
,	TokenNameCOMMA
String	TokenNameIdentifier
panelName	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
Border	TokenNameIdentifier
border	TokenNameIdentifier
=	TokenNameEQUAL
BorderFactory	TokenNameIdentifier
.	TokenNameDOT
createTitledBorder	TokenNameIdentifier
(	TokenNameLPAREN
BorderFactory	TokenNameIdentifier
.	TokenNameDOT
createEtchedBorder	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
,	TokenNameCOMMA
panelName	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
int	TokenNameint
topPad	TokenNameIdentifier
=	TokenNameEQUAL
Resources	TokenNameIdentifier
.	TokenNameDOT
getInteger	TokenNameIdentifier
(	TokenNameLPAREN
CONFIG_TOP_PAD	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
int	TokenNameint
leftPad	TokenNameIdentifier
=	TokenNameEQUAL
Resources	TokenNameIdentifier
.	TokenNameDOT
getInteger	TokenNameIdentifier
(	TokenNameLPAREN
CONFIG_LEFT_PAD	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
int	TokenNameint
bottomPad	TokenNameIdentifier
=	TokenNameEQUAL
Resources	TokenNameIdentifier
.	TokenNameDOT
getInteger	TokenNameIdentifier
(	TokenNameLPAREN
CONFIG_BOTTOM_PAD	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
int	TokenNameint
rightPad	TokenNameIdentifier
=	TokenNameEQUAL
Resources	TokenNameIdentifier
.	TokenNameDOT
getInteger	TokenNameIdentifier
(	TokenNameLPAREN
CONFIG_RIGHT_PAD	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
border	TokenNameIdentifier
=	TokenNameEQUAL
BorderFactory	TokenNameIdentifier
.	TokenNameDOT
createCompoundBorder	TokenNameIdentifier
(	TokenNameLPAREN
border	TokenNameIdentifier
,	TokenNameCOMMA
BorderFactory	TokenNameIdentifier
.	TokenNameDOT
createEmptyBorder	TokenNameIdentifier
(	TokenNameLPAREN
topPad	TokenNameIdentifier
,	TokenNameCOMMA
leftPad	TokenNameIdentifier
,	TokenNameCOMMA
bottomPad	TokenNameIdentifier
,	TokenNameCOMMA
rightPad	TokenNameIdentifier
)	TokenNameRPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
panel	TokenNameIdentifier
.	TokenNameDOT
setBorder	TokenNameIdentifier
(	TokenNameLPAREN
border	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
protected	TokenNameprotected
void	TokenNamevoid
addToPanelAtRow	TokenNameIdentifier
(	TokenNameLPAREN
String	TokenNameIdentifier
label	TokenNameIdentifier
,	TokenNameCOMMA
Document	TokenNameIdentifier
model	TokenNameIdentifier
,	TokenNameCOMMA
String	TokenNameIdentifier
suffix	TokenNameIdentifier
,	TokenNameCOMMA
JGridBagPanel	TokenNameIdentifier
p	TokenNameIdentifier
,	TokenNameCOMMA
int	TokenNameint
row	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
JTextField	TokenNameIdentifier
tf	TokenNameIdentifier
=	TokenNameEQUAL
new	TokenNamenew
JTextField	TokenNameIdentifier
(	TokenNameLPAREN
Resources	TokenNameIdentifier
.	TokenNameDOT
getInteger	TokenNameIdentifier
(	TokenNameLPAREN
CONFIG_TEXT_FIELD_WIDTH	TokenNameIdentifier
)	TokenNameRPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
tf	TokenNameIdentifier
.	TokenNameDOT
setDocument	TokenNameIdentifier
(	TokenNameLPAREN
model	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
p	TokenNameIdentifier
.	TokenNameDOT
add	TokenNameIdentifier
(	TokenNameLPAREN
new	TokenNamenew
JLabel	TokenNameIdentifier
(	TokenNameLPAREN
label	TokenNameIdentifier
)	TokenNameRPAREN
,	TokenNameCOMMA
0	TokenNameIntegerLiteral
,	TokenNameCOMMA
row	TokenNameIdentifier
,	TokenNameCOMMA
1	TokenNameIntegerLiteral
,	TokenNameCOMMA
1	TokenNameIntegerLiteral
,	TokenNameCOMMA
WEST	TokenNameIdentifier
,	TokenNameCOMMA
HORIZONTAL	TokenNameIdentifier
,	TokenNameCOMMA
0	TokenNameIntegerLiteral
,	TokenNameCOMMA
0	TokenNameIntegerLiteral
)	TokenNameRPAREN
;	TokenNameSEMICOLON
p	TokenNameIdentifier
.	TokenNameDOT
add	TokenNameIdentifier
(	TokenNameLPAREN
tf	TokenNameIdentifier
,	TokenNameCOMMA
1	TokenNameIntegerLiteral
,	TokenNameCOMMA
row	TokenNameIdentifier
,	TokenNameCOMMA
1	TokenNameIntegerLiteral
,	TokenNameCOMMA
1	TokenNameIntegerLiteral
,	TokenNameCOMMA
CENTER	TokenNameIdentifier
,	TokenNameCOMMA
HORIZONTAL	TokenNameIdentifier
,	TokenNameCOMMA
1	TokenNameIntegerLiteral
,	TokenNameCOMMA
0	TokenNameIntegerLiteral
)	TokenNameRPAREN
;	TokenNameSEMICOLON
p	TokenNameIdentifier
.	TokenNameDOT
add	TokenNameIdentifier
(	TokenNameLPAREN
new	TokenNamenew
JLabel	TokenNameIdentifier
(	TokenNameLPAREN
suffix	TokenNameIdentifier
)	TokenNameRPAREN
,	TokenNameCOMMA
2	TokenNameIntegerLiteral
,	TokenNameCOMMA
row	TokenNameIdentifier
,	TokenNameCOMMA
1	TokenNameIntegerLiteral
,	TokenNameCOMMA
1	TokenNameIntegerLiteral
,	TokenNameCOMMA
WEST	TokenNameIdentifier
,	TokenNameCOMMA
HORIZONTAL	TokenNameIdentifier
,	TokenNameCOMMA
0	TokenNameIntegerLiteral
,	TokenNameCOMMA
0	TokenNameIntegerLiteral
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
public	TokenNamepublic
AffineTransform	TokenNameIdentifier
getAffineTransform	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
{	TokenNameLBRACE
double	TokenNamedouble
sx	TokenNameIdentifier
=	TokenNameEQUAL
sxModel	TokenNameIdentifier
.	TokenNameDOT
getValue	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
/	TokenNameDIVIDE
100.	TokenNameDoubleLiteral
;	TokenNameSEMICOLON
double	TokenNamedouble
sy	TokenNameIdentifier
=	TokenNameEQUAL
syModel	TokenNameIdentifier
.	TokenNameDOT
getValue	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
/	TokenNameDIVIDE
100.	TokenNameDoubleLiteral
;	TokenNameSEMICOLON
double	TokenNamedouble
theta	TokenNameIdentifier
=	TokenNameEQUAL
rotateModel	TokenNameIdentifier
.	TokenNameDOT
getValue	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
*	TokenNameMULTIPLY
DEG_TO_RAD	TokenNameIdentifier
;	TokenNameSEMICOLON
double	TokenNamedouble
rx	TokenNameIdentifier
=	TokenNameEQUAL
rxModel	TokenNameIdentifier
.	TokenNameDOT
getValue	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
double	TokenNamedouble
ry	TokenNameIdentifier
=	TokenNameEQUAL
ryModel	TokenNameIdentifier
.	TokenNameDOT
getValue	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
double	TokenNamedouble
tx	TokenNameIdentifier
=	TokenNameEQUAL
txModel	TokenNameIdentifier
.	TokenNameDOT
getValue	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
double	TokenNamedouble
ty	TokenNameIdentifier
=	TokenNameEQUAL
tyModel	TokenNameIdentifier
.	TokenNameDOT
getValue	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
double	TokenNamedouble
[	TokenNameLBRACKET
]	TokenNameRBRACKET
m	TokenNameIdentifier
=	TokenNameEQUAL
new	TokenNamenew
double	TokenNamedouble
[	TokenNameLBRACKET
6	TokenNameIntegerLiteral
]	TokenNameRBRACKET
;	TokenNameSEMICOLON
final	TokenNamefinal
double	TokenNamedouble
SIN_THETA	TokenNameIdentifier
=	TokenNameEQUAL
Math	TokenNameIdentifier
.	TokenNameDOT
sin	TokenNameIdentifier
(	TokenNameLPAREN
theta	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
final	TokenNamefinal
double	TokenNamedouble
COS_THETA	TokenNameIdentifier
=	TokenNameEQUAL
Math	TokenNameIdentifier
.	TokenNameDOT
cos	TokenNameIdentifier
(	TokenNameLPAREN
theta	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
m	TokenNameIdentifier
[	TokenNameLBRACKET
0	TokenNameIntegerLiteral
]	TokenNameRBRACKET
=	TokenNameEQUAL
sx	TokenNameIdentifier
*	TokenNameMULTIPLY
COS_THETA	TokenNameIdentifier
;	TokenNameSEMICOLON
m	TokenNameIdentifier
[	TokenNameLBRACKET
1	TokenNameIntegerLiteral
]	TokenNameRBRACKET
=	TokenNameEQUAL
sx	TokenNameIdentifier
*	TokenNameMULTIPLY
SIN_THETA	TokenNameIdentifier
;	TokenNameSEMICOLON
m	TokenNameIdentifier
[	TokenNameLBRACKET
2	TokenNameIntegerLiteral
]	TokenNameRBRACKET
=	TokenNameEQUAL
-	TokenNameMINUS
sy	TokenNameIdentifier
*	TokenNameMULTIPLY
SIN_THETA	TokenNameIdentifier
;	TokenNameSEMICOLON
m	TokenNameIdentifier
[	TokenNameLBRACKET
3	TokenNameIntegerLiteral
]	TokenNameRBRACKET
=	TokenNameEQUAL
sy	TokenNameIdentifier
*	TokenNameMULTIPLY
COS_THETA	TokenNameIdentifier
;	TokenNameSEMICOLON
m	TokenNameIdentifier
[	TokenNameLBRACKET
4	TokenNameIntegerLiteral
]	TokenNameRBRACKET
=	TokenNameEQUAL
tx	TokenNameIdentifier
+	TokenNamePLUS
rx	TokenNameIdentifier
-	TokenNameMINUS
rx	TokenNameIdentifier
*	TokenNameMULTIPLY
COS_THETA	TokenNameIdentifier
+	TokenNamePLUS
ry	TokenNameIdentifier
*	TokenNameMULTIPLY
SIN_THETA	TokenNameIdentifier
;	TokenNameSEMICOLON
m	TokenNameIdentifier
[	TokenNameLBRACKET
5	TokenNameIntegerLiteral
]	TokenNameRBRACKET
=	TokenNameEQUAL
ty	TokenNameIdentifier
+	TokenNamePLUS
ry	TokenNameIdentifier
-	TokenNameMINUS
rx	TokenNameIdentifier
*	TokenNameMULTIPLY
SIN_THETA	TokenNameIdentifier
-	TokenNameMINUS
ry	TokenNameIdentifier
*	TokenNameMULTIPLY
COS_THETA	TokenNameIdentifier
;	TokenNameSEMICOLON
txf	TokenNameIdentifier
=	TokenNameEQUAL
new	TokenNamenew
AffineTransform	TokenNameIdentifier
(	TokenNameLPAREN
m	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
return	TokenNamereturn
txf	TokenNameIdentifier
;	TokenNameSEMICOLON
}	TokenNameRBRACE
public	TokenNamepublic
void	TokenNamevoid
setAffineTransform	TokenNameIdentifier
(	TokenNameLPAREN
AffineTransform	TokenNameIdentifier
txf	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
if	TokenNameif
(	TokenNameLPAREN
txf	TokenNameIdentifier
==	TokenNameEQUAL_EQUAL
null	TokenNamenull
)	TokenNameRPAREN
{	TokenNameLBRACE
txf	TokenNameIdentifier
=	TokenNameEQUAL
new	TokenNamenew
AffineTransform	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
this	TokenNamethis
.	TokenNameDOT
txf	TokenNameIdentifier
=	TokenNameEQUAL
txf	TokenNameIdentifier
;	TokenNameSEMICOLON
double	TokenNamedouble
[	TokenNameLBRACKET
]	TokenNameRBRACKET
m	TokenNameIdentifier
=	TokenNameEQUAL
new	TokenNamenew
double	TokenNamedouble
[	TokenNameLBRACKET
6	TokenNameIntegerLiteral
]	TokenNameRBRACKET
;	TokenNameSEMICOLON
txf	TokenNameIdentifier
.	TokenNameDOT
getMatrix	TokenNameIdentifier
(	TokenNameLPAREN
m	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
txModel	TokenNameIdentifier
.	TokenNameDOT
setValue	TokenNameIdentifier
(	TokenNameLPAREN
m	TokenNameIdentifier
[	TokenNameLBRACKET
4	TokenNameIntegerLiteral
]	TokenNameRBRACKET
)	TokenNameRPAREN
;	TokenNameSEMICOLON
tyModel	TokenNameIdentifier
.	TokenNameDOT
setValue	TokenNameIdentifier
(	TokenNameLPAREN
m	TokenNameIdentifier
[	TokenNameLBRACKET
5	TokenNameIntegerLiteral
]	TokenNameRBRACKET
)	TokenNameRPAREN
;	TokenNameSEMICOLON
double	TokenNamedouble
sx	TokenNameIdentifier
=	TokenNameEQUAL
Math	TokenNameIdentifier
.	TokenNameDOT
sqrt	TokenNameIdentifier
(	TokenNameLPAREN
m	TokenNameIdentifier
[	TokenNameLBRACKET
0	TokenNameIntegerLiteral
]	TokenNameRBRACKET
*	TokenNameMULTIPLY
m	TokenNameIdentifier
[	TokenNameLBRACKET
0	TokenNameIntegerLiteral
]	TokenNameRBRACKET
+	TokenNamePLUS
m	TokenNameIdentifier
[	TokenNameLBRACKET
1	TokenNameIntegerLiteral
]	TokenNameRBRACKET
*	TokenNameMULTIPLY
m	TokenNameIdentifier
[	TokenNameLBRACKET
1	TokenNameIntegerLiteral
]	TokenNameRBRACKET
)	TokenNameRPAREN
;	TokenNameSEMICOLON
double	TokenNamedouble
sy	TokenNameIdentifier
=	TokenNameEQUAL
Math	TokenNameIdentifier
.	TokenNameDOT
sqrt	TokenNameIdentifier
(	TokenNameLPAREN
m	TokenNameIdentifier
[	TokenNameLBRACKET
2	TokenNameIntegerLiteral
]	TokenNameRBRACKET
*	TokenNameMULTIPLY
m	TokenNameIdentifier
[	TokenNameLBRACKET
2	TokenNameIntegerLiteral
]	TokenNameRBRACKET
+	TokenNamePLUS
m	TokenNameIdentifier
[	TokenNameLBRACKET
3	TokenNameIntegerLiteral
]	TokenNameRBRACKET
*	TokenNameMULTIPLY
m	TokenNameIdentifier
[	TokenNameLBRACKET
3	TokenNameIntegerLiteral
]	TokenNameRBRACKET
)	TokenNameRPAREN
;	TokenNameSEMICOLON
sxModel	TokenNameIdentifier
.	TokenNameDOT
setValue	TokenNameIdentifier
(	TokenNameLPAREN
100	TokenNameIntegerLiteral
*	TokenNameMULTIPLY
sx	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
syModel	TokenNameIdentifier
.	TokenNameDOT
setValue	TokenNameIdentifier
(	TokenNameLPAREN
100	TokenNameIntegerLiteral
*	TokenNameMULTIPLY
sy	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
double	TokenNamedouble
theta	TokenNameIdentifier
=	TokenNameEQUAL
0	TokenNameIntegerLiteral
;	TokenNameSEMICOLON
if	TokenNameif
(	TokenNameLPAREN
m	TokenNameIdentifier
[	TokenNameLBRACKET
0	TokenNameIntegerLiteral
]	TokenNameRBRACKET
>	TokenNameGREATER
0	TokenNameIntegerLiteral
)	TokenNameRPAREN
{	TokenNameLBRACE
theta	TokenNameIdentifier
=	TokenNameEQUAL
Math	TokenNameIdentifier
.	TokenNameDOT
atan2	TokenNameIdentifier
(	TokenNameLPAREN
m	TokenNameIdentifier
[	TokenNameLBRACKET
1	TokenNameIntegerLiteral
]	TokenNameRBRACKET
,	TokenNameCOMMA
m	TokenNameIdentifier
[	TokenNameLBRACKET
0	TokenNameIntegerLiteral
]	TokenNameRBRACKET
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
rotateModel	TokenNameIdentifier
.	TokenNameDOT
setValue	TokenNameIdentifier
(	TokenNameLPAREN
RAD_TO_DEG	TokenNameIdentifier
*	TokenNameMULTIPLY
theta	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
rxModel	TokenNameIdentifier
.	TokenNameDOT
setValue	TokenNameIdentifier
(	TokenNameLPAREN
0	TokenNameIntegerLiteral
)	TokenNameRPAREN
;	TokenNameSEMICOLON
ryModel	TokenNameIdentifier
.	TokenNameDOT
setValue	TokenNameIdentifier
(	TokenNameLPAREN
0	TokenNameIntegerLiteral
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
public	TokenNamepublic
static	TokenNamestatic
AffineTransform	TokenNameIdentifier
showDialog	TokenNameIdentifier
(	TokenNameLPAREN
Component	TokenNameIdentifier
cmp	TokenNameIdentifier
,	TokenNameCOMMA
String	TokenNameIdentifier
title	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
final	TokenNamefinal
JAffineTransformChooser	TokenNameIdentifier
pane	TokenNameIdentifier
=	TokenNameEQUAL
new	TokenNamenew
JAffineTransformChooser	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
AffineTransformTracker	TokenNameIdentifier
tracker	TokenNameIdentifier
=	TokenNameEQUAL
new	TokenNamenew
AffineTransformTracker	TokenNameIdentifier
(	TokenNameLPAREN
pane	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
JDialog	TokenNameIdentifier
dialog	TokenNameIdentifier
=	TokenNameEQUAL
new	TokenNamenew
Dialog	TokenNameIdentifier
(	TokenNameLPAREN
cmp	TokenNameIdentifier
,	TokenNameCOMMA
title	TokenNameIdentifier
,	TokenNameCOMMA
true	TokenNametrue
,	TokenNameCOMMA
pane	TokenNameIdentifier
,	TokenNameCOMMA
tracker	TokenNameIdentifier
,	TokenNameCOMMA
null	TokenNamenull
)	TokenNameRPAREN
;	TokenNameSEMICOLON
dialog	TokenNameIdentifier
.	TokenNameDOT
addWindowListener	TokenNameIdentifier
(	TokenNameLPAREN
new	TokenNamenew
Closer	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
dialog	TokenNameIdentifier
.	TokenNameDOT
addComponentListener	TokenNameIdentifier
(	TokenNameLPAREN
new	TokenNamenew
DisposeOnClose	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
dialog	TokenNameIdentifier
.	TokenNameDOT
setVisible	TokenNameIdentifier
(	TokenNameLPAREN
true	TokenNametrue
)	TokenNameRPAREN
;	TokenNameSEMICOLON
return	TokenNamereturn
tracker	TokenNameIdentifier
.	TokenNameDOT
getAffineTransform	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
public	TokenNamepublic
static	TokenNamestatic
Dialog	TokenNameIdentifier
createDialog	TokenNameIdentifier
(	TokenNameLPAREN
Component	TokenNameIdentifier
cmp	TokenNameIdentifier
,	TokenNameCOMMA
String	TokenNameIdentifier
title	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
final	TokenNamefinal
JAffineTransformChooser	TokenNameIdentifier
pane	TokenNameIdentifier
=	TokenNameEQUAL
new	TokenNamenew
JAffineTransformChooser	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
AffineTransformTracker	TokenNameIdentifier
tracker	TokenNameIdentifier
=	TokenNameEQUAL
new	TokenNamenew
AffineTransformTracker	TokenNameIdentifier
(	TokenNameLPAREN
pane	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
Dialog	TokenNameIdentifier
dialog	TokenNameIdentifier
=	TokenNameEQUAL
new	TokenNamenew
Dialog	TokenNameIdentifier
(	TokenNameLPAREN
cmp	TokenNameIdentifier
,	TokenNameCOMMA
title	TokenNameIdentifier
,	TokenNameCOMMA
true	TokenNametrue
,	TokenNameCOMMA
pane	TokenNameIdentifier
,	TokenNameCOMMA
tracker	TokenNameIdentifier
,	TokenNameCOMMA
null	TokenNamenull
)	TokenNameRPAREN
;	TokenNameSEMICOLON
dialog	TokenNameIdentifier
.	TokenNameDOT
addWindowListener	TokenNameIdentifier
(	TokenNameLPAREN
new	TokenNamenew
Closer	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
dialog	TokenNameIdentifier
.	TokenNameDOT
addComponentListener	TokenNameIdentifier
(	TokenNameLPAREN
new	TokenNamenew
DisposeOnClose	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
return	TokenNamereturn
dialog	TokenNameIdentifier
;	TokenNameSEMICOLON
}	TokenNameRBRACE
public	TokenNamepublic
static	TokenNamestatic
void	TokenNamevoid
main	TokenNameIdentifier
(	TokenNameLPAREN
String	TokenNameIdentifier
[	TokenNameLBRACKET
]	TokenNameRBRACKET
args	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
AffineTransform	TokenNameIdentifier
t	TokenNameIdentifier
=	TokenNameEQUAL
showDialog	TokenNameIdentifier
(	TokenNameLPAREN
null	TokenNamenull
,	TokenNameCOMMA
"Hello"	TokenNameStringLiteral
)	TokenNameRPAREN
;	TokenNameSEMICOLON
if	TokenNameif
(	TokenNameLPAREN
t	TokenNameIdentifier
==	TokenNameEQUAL_EQUAL
null	TokenNamenull
)	TokenNameRPAREN
{	TokenNameLBRACE
System	TokenNameIdentifier
.	TokenNameDOT
out	TokenNameIdentifier
.	TokenNameDOT
println	TokenNameIdentifier
(	TokenNameLPAREN
"Cancelled"	TokenNameStringLiteral
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
else	TokenNameelse
{	TokenNameLBRACE
System	TokenNameIdentifier
.	TokenNameDOT
out	TokenNameIdentifier
.	TokenNameDOT
println	TokenNameIdentifier
(	TokenNameLPAREN
"t = "	TokenNameStringLiteral
+	TokenNamePLUS
t	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
}	TokenNameRBRACE
public	TokenNamepublic
static	TokenNamestatic
class	TokenNameclass
Dialog	TokenNameIdentifier
extends	TokenNameextends
JDialog	TokenNameIdentifier
{	TokenNameLBRACE
private	TokenNameprivate
JAffineTransformChooser	TokenNameIdentifier
chooserPane	TokenNameIdentifier
;	TokenNameSEMICOLON
private	TokenNameprivate
AffineTransformTracker	TokenNameIdentifier
tracker	TokenNameIdentifier
;	TokenNameSEMICOLON
public	TokenNamepublic
static	TokenNamestatic
final	TokenNamefinal
String	TokenNameIdentifier
LABEL_OK	TokenNameIdentifier
=	TokenNameEQUAL
"JAffineTransformChooser.label.ok"	TokenNameStringLiteral
;	TokenNameSEMICOLON
public	TokenNamepublic
static	TokenNamestatic
final	TokenNamefinal
String	TokenNameIdentifier
LABEL_CANCEL	TokenNameIdentifier
=	TokenNameEQUAL
"JAffineTransformChooser.label.cancel"	TokenNameStringLiteral
;	TokenNameSEMICOLON
public	TokenNamepublic
static	TokenNamestatic
final	TokenNamefinal
String	TokenNameIdentifier
LABEL_RESET	TokenNameIdentifier
=	TokenNameEQUAL
"JAffineTransformChooser.label.reset"	TokenNameStringLiteral
;	TokenNameSEMICOLON
public	TokenNamepublic
static	TokenNamestatic
final	TokenNamefinal
String	TokenNameIdentifier
ACTION_COMMAND_OK	TokenNameIdentifier
=	TokenNameEQUAL
"OK"	TokenNameStringLiteral
;	TokenNameSEMICOLON
public	TokenNamepublic
static	TokenNamestatic
final	TokenNamefinal
String	TokenNameIdentifier
ACTION_COMMAND_CANCEL	TokenNameIdentifier
=	TokenNameEQUAL
"cancel"	TokenNameStringLiteral
;	TokenNameSEMICOLON
public	TokenNamepublic
Dialog	TokenNameIdentifier
(	TokenNameLPAREN
Component	TokenNameIdentifier
c	TokenNameIdentifier
,	TokenNameCOMMA
String	TokenNameIdentifier
title	TokenNameIdentifier
,	TokenNameCOMMA
boolean	TokenNameboolean
modal	TokenNameIdentifier
,	TokenNameCOMMA
JAffineTransformChooser	TokenNameIdentifier
chooserPane	TokenNameIdentifier
,	TokenNameCOMMA
AffineTransformTracker	TokenNameIdentifier
okListener	TokenNameIdentifier
,	TokenNameCOMMA
ActionListener	TokenNameIdentifier
cancelListener	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
super	TokenNamesuper
(	TokenNameLPAREN
JOptionPane	TokenNameIdentifier
.	TokenNameDOT
getFrameForComponent	TokenNameIdentifier
(	TokenNameLPAREN
c	TokenNameIdentifier
)	TokenNameRPAREN
,	TokenNameCOMMA
title	TokenNameIdentifier
,	TokenNameCOMMA
modal	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
this	TokenNamethis
.	TokenNameDOT
chooserPane	TokenNameIdentifier
=	TokenNameEQUAL
chooserPane	TokenNameIdentifier
;	TokenNameSEMICOLON
this	TokenNamethis
.	TokenNameDOT
tracker	TokenNameIdentifier
=	TokenNameEQUAL
okListener	TokenNameIdentifier
;	TokenNameSEMICOLON
String	TokenNameIdentifier
okString	TokenNameIdentifier
=	TokenNameEQUAL
Resources	TokenNameIdentifier
.	TokenNameDOT
getString	TokenNameIdentifier
(	TokenNameLPAREN
LABEL_OK	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
String	TokenNameIdentifier
cancelString	TokenNameIdentifier
=	TokenNameEQUAL
Resources	TokenNameIdentifier
.	TokenNameDOT
getString	TokenNameIdentifier
(	TokenNameLPAREN
LABEL_CANCEL	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
String	TokenNameIdentifier
resetString	TokenNameIdentifier
=	TokenNameEQUAL
Resources	TokenNameIdentifier
.	TokenNameDOT
getString	TokenNameIdentifier
(	TokenNameLPAREN
LABEL_RESET	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
Container	TokenNameIdentifier
contentPane	TokenNameIdentifier
=	TokenNameEQUAL
getContentPane	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
contentPane	TokenNameIdentifier
.	TokenNameDOT
setLayout	TokenNameIdentifier
(	TokenNameLPAREN
new	TokenNamenew
BorderLayout	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
contentPane	TokenNameIdentifier
.	TokenNameDOT
add	TokenNameIdentifier
(	TokenNameLPAREN
chooserPane	TokenNameIdentifier
,	TokenNameCOMMA
BorderLayout	TokenNameIdentifier
.	TokenNameDOT
CENTER	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
JPanel	TokenNameIdentifier
buttonPane	TokenNameIdentifier
=	TokenNameEQUAL
new	TokenNamenew
JPanel	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
buttonPane	TokenNameIdentifier
.	TokenNameDOT
setLayout	TokenNameIdentifier
(	TokenNameLPAREN
new	TokenNamenew
FlowLayout	TokenNameIdentifier
(	TokenNameLPAREN
FlowLayout	TokenNameIdentifier
.	TokenNameDOT
CENTER	TokenNameIdentifier
)	TokenNameRPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
JButton	TokenNameIdentifier
okButton	TokenNameIdentifier
=	TokenNameEQUAL
new	TokenNamenew
JButton	TokenNameIdentifier
(	TokenNameLPAREN
okString	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
getRootPane	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
.	TokenNameDOT
setDefaultButton	TokenNameIdentifier
(	TokenNameLPAREN
okButton	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
okButton	TokenNameIdentifier
.	TokenNameDOT
setActionCommand	TokenNameIdentifier
(	TokenNameLPAREN
ACTION_COMMAND_OK	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
if	TokenNameif
(	TokenNameLPAREN
okListener	TokenNameIdentifier
!=	TokenNameNOT_EQUAL
null	TokenNamenull
)	TokenNameRPAREN
{	TokenNameLBRACE
okButton	TokenNameIdentifier
.	TokenNameDOT
addActionListener	TokenNameIdentifier
(	TokenNameLPAREN
okListener	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
okButton	TokenNameIdentifier
.	TokenNameDOT
addActionListener	TokenNameIdentifier
(	TokenNameLPAREN
new	TokenNamenew
ActionListener	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
{	TokenNameLBRACE
public	TokenNamepublic
void	TokenNamevoid
actionPerformed	TokenNameIdentifier
(	TokenNameLPAREN
ActionEvent	TokenNameIdentifier
e	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
setVisible	TokenNameIdentifier
(	TokenNameLPAREN
false	TokenNamefalse
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
}	TokenNameRBRACE
)	TokenNameRPAREN
;	TokenNameSEMICOLON
buttonPane	TokenNameIdentifier
.	TokenNameDOT
add	TokenNameIdentifier
(	TokenNameLPAREN
okButton	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
JButton	TokenNameIdentifier
cancelButton	TokenNameIdentifier
=	TokenNameEQUAL
new	TokenNamenew
JButton	TokenNameIdentifier
(	TokenNameLPAREN
cancelString	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
addKeyListener	TokenNameIdentifier
(	TokenNameLPAREN
new	TokenNamenew
KeyAdapter	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
{	TokenNameLBRACE
public	TokenNamepublic
void	TokenNamevoid
keyPressed	TokenNameIdentifier
(	TokenNameLPAREN
KeyEvent	TokenNameIdentifier
evt	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
if	TokenNameif
(	TokenNameLPAREN
evt	TokenNameIdentifier
.	TokenNameDOT
getKeyCode	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
==	TokenNameEQUAL_EQUAL
KeyEvent	TokenNameIdentifier
.	TokenNameDOT
VK_ESCAPE	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
setVisible	TokenNameIdentifier
(	TokenNameLPAREN
false	TokenNamefalse
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
}	TokenNameRBRACE
}	TokenNameRBRACE
)	TokenNameRPAREN
;	TokenNameSEMICOLON
cancelButton	TokenNameIdentifier
.	TokenNameDOT
addActionListener	TokenNameIdentifier
(	TokenNameLPAREN
new	TokenNamenew
ActionListener	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
{	TokenNameLBRACE
public	TokenNamepublic
void	TokenNamevoid
actionPerformed	TokenNameIdentifier
(	TokenNameLPAREN
ActionEvent	TokenNameIdentifier
e	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
setVisible	TokenNameIdentifier
(	TokenNameLPAREN
false	TokenNamefalse
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
}	TokenNameRBRACE
)	TokenNameRPAREN
;	TokenNameSEMICOLON
buttonPane	TokenNameIdentifier
.	TokenNameDOT
add	TokenNameIdentifier
(	TokenNameLPAREN
cancelButton	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
JButton	TokenNameIdentifier
resetButton	TokenNameIdentifier
=	TokenNameEQUAL
new	TokenNamenew
JButton	TokenNameIdentifier
(	TokenNameLPAREN
resetString	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
resetButton	TokenNameIdentifier
.	TokenNameDOT
addActionListener	TokenNameIdentifier
(	TokenNameLPAREN
new	TokenNamenew
ActionListener	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
{	TokenNameLBRACE
public	TokenNamepublic
void	TokenNamevoid
actionPerformed	TokenNameIdentifier
(	TokenNameLPAREN
ActionEvent	TokenNameIdentifier
e	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
reset	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
}	TokenNameRBRACE
)	TokenNameRPAREN
;	TokenNameSEMICOLON
buttonPane	TokenNameIdentifier
.	TokenNameDOT
add	TokenNameIdentifier
(	TokenNameLPAREN
resetButton	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
contentPane	TokenNameIdentifier
.	TokenNameDOT
add	TokenNameIdentifier
(	TokenNameLPAREN
buttonPane	TokenNameIdentifier
,	TokenNameCOMMA
BorderLayout	TokenNameIdentifier
.	TokenNameDOT
SOUTH	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
pack	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
setLocationRelativeTo	TokenNameIdentifier
(	TokenNameLPAREN
c	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
public	TokenNamepublic
void	TokenNamevoid
setVisible	TokenNameIdentifier
(	TokenNameLPAREN
boolean	TokenNameboolean
b	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
if	TokenNameif
(	TokenNameLPAREN
b	TokenNameIdentifier
)	TokenNameRPAREN
tracker	TokenNameIdentifier
.	TokenNameDOT
reset	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
super	TokenNamesuper
.	TokenNameDOT
setVisible	TokenNameIdentifier
(	TokenNameLPAREN
b	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
public	TokenNamepublic
AffineTransform	TokenNameIdentifier
showDialog	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
{	TokenNameLBRACE
this	TokenNamethis
.	TokenNameDOT
setVisible	TokenNameIdentifier
(	TokenNameLPAREN
true	TokenNametrue
)	TokenNameRPAREN
;	TokenNameSEMICOLON
return	TokenNamereturn
tracker	TokenNameIdentifier
.	TokenNameDOT
getAffineTransform	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
public	TokenNamepublic
void	TokenNamevoid
reset	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
{	TokenNameLBRACE
chooserPane	TokenNameIdentifier
.	TokenNameDOT
setAffineTransform	TokenNameIdentifier
(	TokenNameLPAREN
new	TokenNamenew
AffineTransform	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
public	TokenNamepublic
void	TokenNamevoid
setTransform	TokenNameIdentifier
(	TokenNameLPAREN
AffineTransform	TokenNameIdentifier
at	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
if	TokenNameif
(	TokenNameLPAREN
at	TokenNameIdentifier
==	TokenNameEQUAL_EQUAL
null	TokenNamenull
)	TokenNameRPAREN
{	TokenNameLBRACE
at	TokenNameIdentifier
=	TokenNameEQUAL
new	TokenNamenew
AffineTransform	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
chooserPane	TokenNameIdentifier
.	TokenNameDOT
setAffineTransform	TokenNameIdentifier
(	TokenNameLPAREN
at	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
}	TokenNameRBRACE
static	TokenNamestatic
class	TokenNameclass
Closer	TokenNameIdentifier
extends	TokenNameextends
WindowAdapter	TokenNameIdentifier
implements	TokenNameimplements
Serializable	TokenNameIdentifier
{	TokenNameLBRACE
public	TokenNamepublic
void	TokenNamevoid
windowClosing	TokenNameIdentifier
(	TokenNameLPAREN
WindowEvent	TokenNameIdentifier
e	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
Window	TokenNameIdentifier
w	TokenNameIdentifier
=	TokenNameEQUAL
e	TokenNameIdentifier
.	TokenNameDOT
getWindow	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
w	TokenNameIdentifier
.	TokenNameDOT
setVisible	TokenNameIdentifier
(	TokenNameLPAREN
false	TokenNamefalse
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
}	TokenNameRBRACE
static	TokenNamestatic
class	TokenNameclass
DisposeOnClose	TokenNameIdentifier
extends	TokenNameextends
ComponentAdapter	TokenNameIdentifier
implements	TokenNameimplements
Serializable	TokenNameIdentifier
{	TokenNameLBRACE
public	TokenNamepublic
void	TokenNamevoid
componentHidden	TokenNameIdentifier
(	TokenNameLPAREN
ComponentEvent	TokenNameIdentifier
e	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
Window	TokenNameIdentifier
w	TokenNameIdentifier
=	TokenNameEQUAL
(	TokenNameLPAREN
Window	TokenNameIdentifier
)	TokenNameRPAREN
e	TokenNameIdentifier
.	TokenNameDOT
getComponent	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
w	TokenNameIdentifier
.	TokenNameDOT
dispose	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
}	TokenNameRBRACE
}	TokenNameRBRACE
class	TokenNameclass
AffineTransformTracker	TokenNameIdentifier
implements	TokenNameimplements
ActionListener	TokenNameIdentifier
,	TokenNameCOMMA
Serializable	TokenNameIdentifier
{	TokenNameLBRACE
JAffineTransformChooser	TokenNameIdentifier
chooser	TokenNameIdentifier
;	TokenNameSEMICOLON
AffineTransform	TokenNameIdentifier
txf	TokenNameIdentifier
;	TokenNameSEMICOLON
public	TokenNamepublic
AffineTransformTracker	TokenNameIdentifier
(	TokenNameLPAREN
JAffineTransformChooser	TokenNameIdentifier
c	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
chooser	TokenNameIdentifier
=	TokenNameEQUAL
c	TokenNameIdentifier
;	TokenNameSEMICOLON
}	TokenNameRBRACE
public	TokenNamepublic
void	TokenNamevoid
actionPerformed	TokenNameIdentifier
(	TokenNameLPAREN
ActionEvent	TokenNameIdentifier
e	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
txf	TokenNameIdentifier
=	TokenNameEQUAL
chooser	TokenNameIdentifier
.	TokenNameDOT
getAffineTransform	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
public	TokenNamepublic
AffineTransform	TokenNameIdentifier
getAffineTransform	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
{	TokenNameLBRACE
return	TokenNamereturn
txf	TokenNameIdentifier
;	TokenNameSEMICOLON
}	TokenNameRBRACE
public	TokenNamepublic
void	TokenNamevoid
reset	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
{	TokenNameLBRACE
txf	TokenNameIdentifier
=	TokenNameEQUAL
null	TokenNamenull
;	TokenNameSEMICOLON
}	TokenNameRBRACE
}	TokenNameRBRACE
