package	TokenNamepackage
org	TokenNameIdentifier
.	TokenNameDOT
apache	TokenNameIdentifier
.	TokenNameDOT
xpath	TokenNameIdentifier
.	TokenNameDOT
patterns	TokenNameIdentifier
;	TokenNameSEMICOLON
public	TokenNamepublic
interface	TokenNameinterface
NodeTestFilter	TokenNameIdentifier
{	TokenNameLBRACE
void	TokenNamevoid
setNodeTest	TokenNameIdentifier
(	TokenNameLPAREN
NodeTest	TokenNameIdentifier
nodeTest	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
