package	TokenNamepackage
org	TokenNameIdentifier
.	TokenNameDOT
apache	TokenNameIdentifier
.	TokenNameDOT
batik	TokenNameIdentifier
.	TokenNameDOT
swing	TokenNameIdentifier
.	TokenNameDOT
gvt	TokenNameIdentifier
;	TokenNameSEMICOLON
public	TokenNamepublic
class	TokenNameclass
JGVTComponent	TokenNameIdentifier
extends	TokenNameextends
AbstractJGVTComponent	TokenNameIdentifier
{	TokenNameLBRACE
public	TokenNamepublic
JGVTComponent	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
{	TokenNameLBRACE
}	TokenNameRBRACE
public	TokenNamepublic
JGVTComponent	TokenNameIdentifier
(	TokenNameLPAREN
boolean	TokenNameboolean
eventsEnabled	TokenNameIdentifier
,	TokenNameCOMMA
boolean	TokenNameboolean
selectableText	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
super	TokenNamesuper
(	TokenNameLPAREN
eventsEnabled	TokenNameIdentifier
,	TokenNameCOMMA
selectableText	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
protected	TokenNameprotected
class	TokenNameclass
ExtendedListener	TokenNameIdentifier
extends	TokenNameextends
Listener	TokenNameIdentifier
{	TokenNameLBRACE
}	TokenNameRBRACE
}	TokenNameRBRACE
