package	TokenNamepackage
org	TokenNameIdentifier
.	TokenNameDOT
apache	TokenNameIdentifier
.	TokenNameDOT
batik	TokenNameIdentifier
.	TokenNameDOT
css	TokenNameIdentifier
.	TokenNameDOT
engine	TokenNameIdentifier
.	TokenNameDOT
value	TokenNameIdentifier
.	TokenNameDOT
css2	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
org	TokenNameIdentifier
.	TokenNameDOT
apache	TokenNameIdentifier
.	TokenNameDOT
batik	TokenNameIdentifier
.	TokenNameDOT
css	TokenNameIdentifier
.	TokenNameDOT
engine	TokenNameIdentifier
.	TokenNameDOT
CSSContext	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
org	TokenNameIdentifier
.	TokenNameDOT
apache	TokenNameIdentifier
.	TokenNameDOT
batik	TokenNameIdentifier
.	TokenNameDOT
css	TokenNameIdentifier
.	TokenNameDOT
engine	TokenNameIdentifier
.	TokenNameDOT
CSSEngine	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
org	TokenNameIdentifier
.	TokenNameDOT
apache	TokenNameIdentifier
.	TokenNameDOT
batik	TokenNameIdentifier
.	TokenNameDOT
css	TokenNameIdentifier
.	TokenNameDOT
engine	TokenNameIdentifier
.	TokenNameDOT
CSSStylableElement	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
org	TokenNameIdentifier
.	TokenNameDOT
apache	TokenNameIdentifier
.	TokenNameDOT
batik	TokenNameIdentifier
.	TokenNameDOT
css	TokenNameIdentifier
.	TokenNameDOT
engine	TokenNameIdentifier
.	TokenNameDOT
StyleMap	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
org	TokenNameIdentifier
.	TokenNameDOT
apache	TokenNameIdentifier
.	TokenNameDOT
batik	TokenNameIdentifier
.	TokenNameDOT
css	TokenNameIdentifier
.	TokenNameDOT
engine	TokenNameIdentifier
.	TokenNameDOT
value	TokenNameIdentifier
.	TokenNameDOT
IdentifierManager	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
org	TokenNameIdentifier
.	TokenNameDOT
apache	TokenNameIdentifier
.	TokenNameDOT
batik	TokenNameIdentifier
.	TokenNameDOT
css	TokenNameIdentifier
.	TokenNameDOT
engine	TokenNameIdentifier
.	TokenNameDOT
value	TokenNameIdentifier
.	TokenNameDOT
StringMap	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
org	TokenNameIdentifier
.	TokenNameDOT
apache	TokenNameIdentifier
.	TokenNameDOT
batik	TokenNameIdentifier
.	TokenNameDOT
css	TokenNameIdentifier
.	TokenNameDOT
engine	TokenNameIdentifier
.	TokenNameDOT
value	TokenNameIdentifier
.	TokenNameDOT
Value	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
org	TokenNameIdentifier
.	TokenNameDOT
apache	TokenNameIdentifier
.	TokenNameDOT
batik	TokenNameIdentifier
.	TokenNameDOT
css	TokenNameIdentifier
.	TokenNameDOT
engine	TokenNameIdentifier
.	TokenNameDOT
value	TokenNameIdentifier
.	TokenNameDOT
ValueConstants	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
org	TokenNameIdentifier
.	TokenNameDOT
apache	TokenNameIdentifier
.	TokenNameDOT
batik	TokenNameIdentifier
.	TokenNameDOT
css	TokenNameIdentifier
.	TokenNameDOT
engine	TokenNameIdentifier
.	TokenNameDOT
value	TokenNameIdentifier
.	TokenNameDOT
ValueManager	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
org	TokenNameIdentifier
.	TokenNameDOT
apache	TokenNameIdentifier
.	TokenNameDOT
batik	TokenNameIdentifier
.	TokenNameDOT
util	TokenNameIdentifier
.	TokenNameDOT
CSSConstants	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
org	TokenNameIdentifier
.	TokenNameDOT
apache	TokenNameIdentifier
.	TokenNameDOT
batik	TokenNameIdentifier
.	TokenNameDOT
util	TokenNameIdentifier
.	TokenNameDOT
SVGTypes	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
org	TokenNameIdentifier
.	TokenNameDOT
w3c	TokenNameIdentifier
.	TokenNameDOT
css	TokenNameIdentifier
.	TokenNameDOT
sac	TokenNameIdentifier
.	TokenNameDOT
LexicalUnit	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
org	TokenNameIdentifier
.	TokenNameDOT
w3c	TokenNameIdentifier
.	TokenNameDOT
dom	TokenNameIdentifier
.	TokenNameDOT
DOMException	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
org	TokenNameIdentifier
.	TokenNameDOT
w3c	TokenNameIdentifier
.	TokenNameDOT
dom	TokenNameIdentifier
.	TokenNameDOT
css	TokenNameIdentifier
.	TokenNameDOT
CSSPrimitiveValue	TokenNameIdentifier
;	TokenNameSEMICOLON
public	TokenNamepublic
class	TokenNameclass
FontWeightManager	TokenNameIdentifier
extends	TokenNameextends
IdentifierManager	TokenNameIdentifier
{	TokenNameLBRACE
protected	TokenNameprotected
static	TokenNamestatic
final	TokenNamefinal
StringMap	TokenNameIdentifier
values	TokenNameIdentifier
=	TokenNameEQUAL
new	TokenNamenew
StringMap	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
static	TokenNamestatic
{	TokenNameLBRACE
values	TokenNameIdentifier
.	TokenNameDOT
put	TokenNameIdentifier
(	TokenNameLPAREN
CSSConstants	TokenNameIdentifier
.	TokenNameDOT
CSS_ALL_VALUE	TokenNameIdentifier
,	TokenNameCOMMA
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
ALL_VALUE	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
values	TokenNameIdentifier
.	TokenNameDOT
put	TokenNameIdentifier
(	TokenNameLPAREN
CSSConstants	TokenNameIdentifier
.	TokenNameDOT
CSS_BOLD_VALUE	TokenNameIdentifier
,	TokenNameCOMMA
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
BOLD_VALUE	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
values	TokenNameIdentifier
.	TokenNameDOT
put	TokenNameIdentifier
(	TokenNameLPAREN
CSSConstants	TokenNameIdentifier
.	TokenNameDOT
CSS_BOLDER_VALUE	TokenNameIdentifier
,	TokenNameCOMMA
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
BOLDER_VALUE	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
values	TokenNameIdentifier
.	TokenNameDOT
put	TokenNameIdentifier
(	TokenNameLPAREN
CSSConstants	TokenNameIdentifier
.	TokenNameDOT
CSS_LIGHTER_VALUE	TokenNameIdentifier
,	TokenNameCOMMA
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
LIGHTER_VALUE	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
values	TokenNameIdentifier
.	TokenNameDOT
put	TokenNameIdentifier
(	TokenNameLPAREN
CSSConstants	TokenNameIdentifier
.	TokenNameDOT
CSS_NORMAL_VALUE	TokenNameIdentifier
,	TokenNameCOMMA
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
NORMAL_VALUE	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
public	TokenNamepublic
boolean	TokenNameboolean
isInheritedProperty	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
{	TokenNameLBRACE
return	TokenNamereturn
true	TokenNametrue
;	TokenNameSEMICOLON
}	TokenNameRBRACE
public	TokenNamepublic
boolean	TokenNameboolean
isAnimatableProperty	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
{	TokenNameLBRACE
return	TokenNamereturn
true	TokenNametrue
;	TokenNameSEMICOLON
}	TokenNameRBRACE
public	TokenNamepublic
boolean	TokenNameboolean
isAdditiveProperty	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
{	TokenNameLBRACE
return	TokenNamereturn
false	TokenNamefalse
;	TokenNameSEMICOLON
}	TokenNameRBRACE
public	TokenNamepublic
int	TokenNameint
getPropertyType	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
{	TokenNameLBRACE
return	TokenNamereturn
SVGTypes	TokenNameIdentifier
.	TokenNameDOT
TYPE_FONT_WEIGHT_VALUE	TokenNameIdentifier
;	TokenNameSEMICOLON
}	TokenNameRBRACE
public	TokenNamepublic
String	TokenNameIdentifier
getPropertyName	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
{	TokenNameLBRACE
return	TokenNamereturn
CSSConstants	TokenNameIdentifier
.	TokenNameDOT
CSS_FONT_WEIGHT_PROPERTY	TokenNameIdentifier
;	TokenNameSEMICOLON
}	TokenNameRBRACE
public	TokenNamepublic
Value	TokenNameIdentifier
getDefaultValue	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
{	TokenNameLBRACE
return	TokenNamereturn
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
NORMAL_VALUE	TokenNameIdentifier
;	TokenNameSEMICOLON
}	TokenNameRBRACE
public	TokenNamepublic
Value	TokenNameIdentifier
createValue	TokenNameIdentifier
(	TokenNameLPAREN
LexicalUnit	TokenNameIdentifier
lu	TokenNameIdentifier
,	TokenNameCOMMA
CSSEngine	TokenNameIdentifier
engine	TokenNameIdentifier
)	TokenNameRPAREN
throws	TokenNamethrows
DOMException	TokenNameIdentifier
{	TokenNameLBRACE
if	TokenNameif
(	TokenNameLPAREN
lu	TokenNameIdentifier
.	TokenNameDOT
getLexicalUnitType	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
==	TokenNameEQUAL_EQUAL
LexicalUnit	TokenNameIdentifier
.	TokenNameDOT
SAC_INTEGER	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
int	TokenNameint
i	TokenNameIdentifier
=	TokenNameEQUAL
lu	TokenNameIdentifier
.	TokenNameDOT
getIntegerValue	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
switch	TokenNameswitch
(	TokenNameLPAREN
i	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
case	TokenNamecase
100	TokenNameIntegerLiteral
:	TokenNameCOLON
return	TokenNamereturn
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
NUMBER_100	TokenNameIdentifier
;	TokenNameSEMICOLON
case	TokenNamecase
200	TokenNameIntegerLiteral
:	TokenNameCOLON
return	TokenNamereturn
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
NUMBER_200	TokenNameIdentifier
;	TokenNameSEMICOLON
case	TokenNamecase
300	TokenNameIntegerLiteral
:	TokenNameCOLON
return	TokenNamereturn
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
NUMBER_300	TokenNameIdentifier
;	TokenNameSEMICOLON
case	TokenNamecase
400	TokenNameIntegerLiteral
:	TokenNameCOLON
return	TokenNamereturn
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
NUMBER_400	TokenNameIdentifier
;	TokenNameSEMICOLON
case	TokenNamecase
500	TokenNameIntegerLiteral
:	TokenNameCOLON
return	TokenNamereturn
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
NUMBER_500	TokenNameIdentifier
;	TokenNameSEMICOLON
case	TokenNamecase
600	TokenNameIntegerLiteral
:	TokenNameCOLON
return	TokenNamereturn
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
NUMBER_600	TokenNameIdentifier
;	TokenNameSEMICOLON
case	TokenNamecase
700	TokenNameIntegerLiteral
:	TokenNameCOLON
return	TokenNamereturn
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
NUMBER_700	TokenNameIdentifier
;	TokenNameSEMICOLON
case	TokenNamecase
800	TokenNameIntegerLiteral
:	TokenNameCOLON
return	TokenNamereturn
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
NUMBER_800	TokenNameIdentifier
;	TokenNameSEMICOLON
case	TokenNamecase
900	TokenNameIntegerLiteral
:	TokenNameCOLON
return	TokenNamereturn
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
NUMBER_900	TokenNameIdentifier
;	TokenNameSEMICOLON
}	TokenNameRBRACE
throw	TokenNamethrow
createInvalidFloatValueDOMException	TokenNameIdentifier
(	TokenNameLPAREN
i	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
return	TokenNamereturn
super	TokenNamesuper
.	TokenNameDOT
createValue	TokenNameIdentifier
(	TokenNameLPAREN
lu	TokenNameIdentifier
,	TokenNameCOMMA
engine	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
public	TokenNamepublic
Value	TokenNameIdentifier
createFloatValue	TokenNameIdentifier
(	TokenNameLPAREN
short	TokenNameshort
type	TokenNameIdentifier
,	TokenNameCOMMA
float	TokenNamefloat
floatValue	TokenNameIdentifier
)	TokenNameRPAREN
throws	TokenNamethrows
DOMException	TokenNameIdentifier
{	TokenNameLBRACE
if	TokenNameif
(	TokenNameLPAREN
type	TokenNameIdentifier
==	TokenNameEQUAL_EQUAL
CSSPrimitiveValue	TokenNameIdentifier
.	TokenNameDOT
CSS_NUMBER	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
int	TokenNameint
i	TokenNameIdentifier
=	TokenNameEQUAL
(	TokenNameLPAREN
int	TokenNameint
)	TokenNameRPAREN
floatValue	TokenNameIdentifier
;	TokenNameSEMICOLON
if	TokenNameif
(	TokenNameLPAREN
floatValue	TokenNameIdentifier
==	TokenNameEQUAL_EQUAL
i	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
switch	TokenNameswitch
(	TokenNameLPAREN
i	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
case	TokenNamecase
100	TokenNameIntegerLiteral
:	TokenNameCOLON
return	TokenNamereturn
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
NUMBER_100	TokenNameIdentifier
;	TokenNameSEMICOLON
case	TokenNamecase
200	TokenNameIntegerLiteral
:	TokenNameCOLON
return	TokenNamereturn
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
NUMBER_200	TokenNameIdentifier
;	TokenNameSEMICOLON
case	TokenNamecase
300	TokenNameIntegerLiteral
:	TokenNameCOLON
return	TokenNamereturn
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
NUMBER_300	TokenNameIdentifier
;	TokenNameSEMICOLON
case	TokenNamecase
400	TokenNameIntegerLiteral
:	TokenNameCOLON
return	TokenNamereturn
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
NUMBER_400	TokenNameIdentifier
;	TokenNameSEMICOLON
case	TokenNamecase
500	TokenNameIntegerLiteral
:	TokenNameCOLON
return	TokenNamereturn
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
NUMBER_500	TokenNameIdentifier
;	TokenNameSEMICOLON
case	TokenNamecase
600	TokenNameIntegerLiteral
:	TokenNameCOLON
return	TokenNamereturn
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
NUMBER_600	TokenNameIdentifier
;	TokenNameSEMICOLON
case	TokenNamecase
700	TokenNameIntegerLiteral
:	TokenNameCOLON
return	TokenNamereturn
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
NUMBER_700	TokenNameIdentifier
;	TokenNameSEMICOLON
case	TokenNamecase
800	TokenNameIntegerLiteral
:	TokenNameCOLON
return	TokenNamereturn
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
NUMBER_800	TokenNameIdentifier
;	TokenNameSEMICOLON
case	TokenNamecase
900	TokenNameIntegerLiteral
:	TokenNameCOLON
return	TokenNamereturn
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
NUMBER_900	TokenNameIdentifier
;	TokenNameSEMICOLON
}	TokenNameRBRACE
}	TokenNameRBRACE
}	TokenNameRBRACE
throw	TokenNamethrow
createInvalidFloatValueDOMException	TokenNameIdentifier
(	TokenNameLPAREN
floatValue	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
public	TokenNamepublic
Value	TokenNameIdentifier
computeValue	TokenNameIdentifier
(	TokenNameLPAREN
CSSStylableElement	TokenNameIdentifier
elt	TokenNameIdentifier
,	TokenNameCOMMA
String	TokenNameIdentifier
pseudo	TokenNameIdentifier
,	TokenNameCOMMA
CSSEngine	TokenNameIdentifier
engine	TokenNameIdentifier
,	TokenNameCOMMA
int	TokenNameint
idx	TokenNameIdentifier
,	TokenNameCOMMA
StyleMap	TokenNameIdentifier
sm	TokenNameIdentifier
,	TokenNameCOMMA
Value	TokenNameIdentifier
value	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
if	TokenNameif
(	TokenNameLPAREN
value	TokenNameIdentifier
==	TokenNameEQUAL_EQUAL
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
BOLDER_VALUE	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
sm	TokenNameIdentifier
.	TokenNameDOT
putParentRelative	TokenNameIdentifier
(	TokenNameLPAREN
idx	TokenNameIdentifier
,	TokenNameCOMMA
true	TokenNametrue
)	TokenNameRPAREN
;	TokenNameSEMICOLON
CSSContext	TokenNameIdentifier
ctx	TokenNameIdentifier
=	TokenNameEQUAL
engine	TokenNameIdentifier
.	TokenNameDOT
getCSSContext	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
CSSStylableElement	TokenNameIdentifier
p	TokenNameIdentifier
=	TokenNameEQUAL
CSSEngine	TokenNameIdentifier
.	TokenNameDOT
getParentCSSStylableElement	TokenNameIdentifier
(	TokenNameLPAREN
elt	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
float	TokenNamefloat
fw	TokenNameIdentifier
;	TokenNameSEMICOLON
if	TokenNameif
(	TokenNameLPAREN
p	TokenNameIdentifier
==	TokenNameEQUAL_EQUAL
null	TokenNamenull
)	TokenNameRPAREN
{	TokenNameLBRACE
fw	TokenNameIdentifier
=	TokenNameEQUAL
400	TokenNameIntegerLiteral
;	TokenNameSEMICOLON
}	TokenNameRBRACE
else	TokenNameelse
{	TokenNameLBRACE
Value	TokenNameIdentifier
v	TokenNameIdentifier
=	TokenNameEQUAL
engine	TokenNameIdentifier
.	TokenNameDOT
getComputedStyle	TokenNameIdentifier
(	TokenNameLPAREN
p	TokenNameIdentifier
,	TokenNameCOMMA
pseudo	TokenNameIdentifier
,	TokenNameCOMMA
idx	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
fw	TokenNameIdentifier
=	TokenNameEQUAL
v	TokenNameIdentifier
.	TokenNameDOT
getFloatValue	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
return	TokenNamereturn
createFontWeight	TokenNameIdentifier
(	TokenNameLPAREN
ctx	TokenNameIdentifier
.	TokenNameDOT
getBolderFontWeight	TokenNameIdentifier
(	TokenNameLPAREN
fw	TokenNameIdentifier
)	TokenNameRPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
else	TokenNameelse
if	TokenNameif
(	TokenNameLPAREN
value	TokenNameIdentifier
==	TokenNameEQUAL_EQUAL
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
LIGHTER_VALUE	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
sm	TokenNameIdentifier
.	TokenNameDOT
putParentRelative	TokenNameIdentifier
(	TokenNameLPAREN
idx	TokenNameIdentifier
,	TokenNameCOMMA
true	TokenNametrue
)	TokenNameRPAREN
;	TokenNameSEMICOLON
CSSContext	TokenNameIdentifier
ctx	TokenNameIdentifier
=	TokenNameEQUAL
engine	TokenNameIdentifier
.	TokenNameDOT
getCSSContext	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
CSSStylableElement	TokenNameIdentifier
p	TokenNameIdentifier
=	TokenNameEQUAL
CSSEngine	TokenNameIdentifier
.	TokenNameDOT
getParentCSSStylableElement	TokenNameIdentifier
(	TokenNameLPAREN
elt	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
float	TokenNamefloat
fw	TokenNameIdentifier
;	TokenNameSEMICOLON
if	TokenNameif
(	TokenNameLPAREN
p	TokenNameIdentifier
==	TokenNameEQUAL_EQUAL
null	TokenNamenull
)	TokenNameRPAREN
{	TokenNameLBRACE
fw	TokenNameIdentifier
=	TokenNameEQUAL
400	TokenNameIntegerLiteral
;	TokenNameSEMICOLON
}	TokenNameRBRACE
else	TokenNameelse
{	TokenNameLBRACE
Value	TokenNameIdentifier
v	TokenNameIdentifier
=	TokenNameEQUAL
engine	TokenNameIdentifier
.	TokenNameDOT
getComputedStyle	TokenNameIdentifier
(	TokenNameLPAREN
p	TokenNameIdentifier
,	TokenNameCOMMA
pseudo	TokenNameIdentifier
,	TokenNameCOMMA
idx	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
fw	TokenNameIdentifier
=	TokenNameEQUAL
v	TokenNameIdentifier
.	TokenNameDOT
getFloatValue	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
return	TokenNamereturn
createFontWeight	TokenNameIdentifier
(	TokenNameLPAREN
ctx	TokenNameIdentifier
.	TokenNameDOT
getLighterFontWeight	TokenNameIdentifier
(	TokenNameLPAREN
fw	TokenNameIdentifier
)	TokenNameRPAREN
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
else	TokenNameelse
if	TokenNameif
(	TokenNameLPAREN
value	TokenNameIdentifier
==	TokenNameEQUAL_EQUAL
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
NORMAL_VALUE	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
return	TokenNamereturn
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
NUMBER_400	TokenNameIdentifier
;	TokenNameSEMICOLON
}	TokenNameRBRACE
else	TokenNameelse
if	TokenNameif
(	TokenNameLPAREN
value	TokenNameIdentifier
==	TokenNameEQUAL_EQUAL
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
BOLD_VALUE	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
return	TokenNamereturn
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
NUMBER_700	TokenNameIdentifier
;	TokenNameSEMICOLON
}	TokenNameRBRACE
return	TokenNamereturn
value	TokenNameIdentifier
;	TokenNameSEMICOLON
}	TokenNameRBRACE
protected	TokenNameprotected
Value	TokenNameIdentifier
createFontWeight	TokenNameIdentifier
(	TokenNameLPAREN
float	TokenNamefloat
f	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
switch	TokenNameswitch
(	TokenNameLPAREN
(	TokenNameLPAREN
int	TokenNameint
)	TokenNameRPAREN
f	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
case	TokenNamecase
100	TokenNameIntegerLiteral
:	TokenNameCOLON
return	TokenNamereturn
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
NUMBER_100	TokenNameIdentifier
;	TokenNameSEMICOLON
case	TokenNamecase
200	TokenNameIntegerLiteral
:	TokenNameCOLON
return	TokenNamereturn
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
NUMBER_200	TokenNameIdentifier
;	TokenNameSEMICOLON
case	TokenNamecase
300	TokenNameIntegerLiteral
:	TokenNameCOLON
return	TokenNamereturn
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
NUMBER_300	TokenNameIdentifier
;	TokenNameSEMICOLON
case	TokenNamecase
400	TokenNameIntegerLiteral
:	TokenNameCOLON
return	TokenNamereturn
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
NUMBER_400	TokenNameIdentifier
;	TokenNameSEMICOLON
case	TokenNamecase
500	TokenNameIntegerLiteral
:	TokenNameCOLON
return	TokenNamereturn
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
NUMBER_500	TokenNameIdentifier
;	TokenNameSEMICOLON
case	TokenNamecase
600	TokenNameIntegerLiteral
:	TokenNameCOLON
return	TokenNamereturn
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
NUMBER_600	TokenNameIdentifier
;	TokenNameSEMICOLON
case	TokenNamecase
700	TokenNameIntegerLiteral
:	TokenNameCOLON
return	TokenNamereturn
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
NUMBER_700	TokenNameIdentifier
;	TokenNameSEMICOLON
case	TokenNamecase
800	TokenNameIntegerLiteral
:	TokenNameCOLON
return	TokenNamereturn
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
NUMBER_800	TokenNameIdentifier
;	TokenNameSEMICOLON
default	TokenNamedefault
:	TokenNameCOLON
return	TokenNamereturn
ValueConstants	TokenNameIdentifier
.	TokenNameDOT
NUMBER_900	TokenNameIdentifier
;	TokenNameSEMICOLON
}	TokenNameRBRACE
}	TokenNameRBRACE
public	TokenNamepublic
StringMap	TokenNameIdentifier
getIdentifiers	TokenNameIdentifier
(	TokenNameLPAREN
)	TokenNameRPAREN
{	TokenNameLBRACE
return	TokenNamereturn
values	TokenNameIdentifier
;	TokenNameSEMICOLON
}	TokenNameRBRACE
}	TokenNameRBRACE
