package	TokenNamepackage
org	TokenNameIdentifier
.	TokenNameDOT
apache	TokenNameIdentifier
.	TokenNameDOT
batik	TokenNameIdentifier
.	TokenNameDOT
transcoder	TokenNameIdentifier
.	TokenNameDOT
wmf	TokenNameIdentifier
.	TokenNameDOT
tosvg	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
java	TokenNameIdentifier
.	TokenNameDOT
io	TokenNameIdentifier
.	TokenNameDOT
UnsupportedEncodingException	TokenNameIdentifier
;	TokenNameSEMICOLON
import	TokenNameimport
org	TokenNameIdentifier
.	TokenNameDOT
apache	TokenNameIdentifier
.	TokenNameDOT
batik	TokenNameIdentifier
.	TokenNameDOT
transcoder	TokenNameIdentifier
.	TokenNameDOT
wmf	TokenNameIdentifier
.	TokenNameDOT
WMFConstants	TokenNameIdentifier
;	TokenNameSEMICOLON
public	TokenNamepublic
class	TokenNameclass
WMFUtilities	TokenNameIdentifier
{	TokenNameLBRACE
public	TokenNamepublic
static	TokenNamestatic
String	TokenNameIdentifier
decodeString	TokenNameIdentifier
(	TokenNameLPAREN
WMFFont	TokenNameIdentifier
wmfFont	TokenNameIdentifier
,	TokenNameCOMMA
byte	TokenNamebyte
[	TokenNameLBRACKET
]	TokenNameRBRACKET
bstr	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
try	TokenNametry
{	TokenNameLBRACE
switch	TokenNameswitch
(	TokenNameLPAREN
wmfFont	TokenNameIdentifier
.	TokenNameDOT
charset	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
case	TokenNamecase
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
META_CHARSET_ANSI	TokenNameIdentifier
:	TokenNameCOLON
return	TokenNamereturn
new	TokenNamenew
String	TokenNameIdentifier
(	TokenNameLPAREN
bstr	TokenNameIdentifier
,	TokenNameCOMMA
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
CHARSET_ANSI	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
case	TokenNamecase
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
META_CHARSET_DEFAULT	TokenNameIdentifier
:	TokenNameCOLON
return	TokenNamereturn
new	TokenNamenew
String	TokenNameIdentifier
(	TokenNameLPAREN
bstr	TokenNameIdentifier
,	TokenNameCOMMA
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
CHARSET_DEFAULT	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
case	TokenNamecase
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
META_CHARSET_SHIFTJIS	TokenNameIdentifier
:	TokenNameCOLON
return	TokenNamereturn
new	TokenNamenew
String	TokenNameIdentifier
(	TokenNameLPAREN
bstr	TokenNameIdentifier
,	TokenNameCOMMA
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
CHARSET_SHIFTJIS	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
case	TokenNamecase
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
META_CHARSET_HANGUL	TokenNameIdentifier
:	TokenNameCOLON
return	TokenNamereturn
new	TokenNamenew
String	TokenNameIdentifier
(	TokenNameLPAREN
bstr	TokenNameIdentifier
,	TokenNameCOMMA
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
CHARSET_HANGUL	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
case	TokenNamecase
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
META_CHARSET_JOHAB	TokenNameIdentifier
:	TokenNameCOLON
return	TokenNamereturn
new	TokenNamenew
String	TokenNameIdentifier
(	TokenNameLPAREN
bstr	TokenNameIdentifier
,	TokenNameCOMMA
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
CHARSET_JOHAB	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
case	TokenNamecase
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
META_CHARSET_GB2312	TokenNameIdentifier
:	TokenNameCOLON
return	TokenNamereturn
new	TokenNamenew
String	TokenNameIdentifier
(	TokenNameLPAREN
bstr	TokenNameIdentifier
,	TokenNameCOMMA
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
CHARSET_GB2312	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
case	TokenNamecase
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
META_CHARSET_CHINESEBIG5	TokenNameIdentifier
:	TokenNameCOLON
return	TokenNamereturn
new	TokenNamenew
String	TokenNameIdentifier
(	TokenNameLPAREN
bstr	TokenNameIdentifier
,	TokenNameCOMMA
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
CHARSET_CHINESEBIG5	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
case	TokenNamecase
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
META_CHARSET_GREEK	TokenNameIdentifier
:	TokenNameCOLON
return	TokenNamereturn
new	TokenNamenew
String	TokenNameIdentifier
(	TokenNameLPAREN
bstr	TokenNameIdentifier
,	TokenNameCOMMA
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
CHARSET_GREEK	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
case	TokenNamecase
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
META_CHARSET_TURKISH	TokenNameIdentifier
:	TokenNameCOLON
return	TokenNamereturn
new	TokenNamenew
String	TokenNameIdentifier
(	TokenNameLPAREN
bstr	TokenNameIdentifier
,	TokenNameCOMMA
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
CHARSET_TURKISH	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
case	TokenNamecase
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
META_CHARSET_VIETNAMESE	TokenNameIdentifier
:	TokenNameCOLON
return	TokenNamereturn
new	TokenNamenew
String	TokenNameIdentifier
(	TokenNameLPAREN
bstr	TokenNameIdentifier
,	TokenNameCOMMA
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
CHARSET_VIETNAMESE	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
case	TokenNamecase
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
META_CHARSET_HEBREW	TokenNameIdentifier
:	TokenNameCOLON
return	TokenNamereturn
new	TokenNamenew
String	TokenNameIdentifier
(	TokenNameLPAREN
bstr	TokenNameIdentifier
,	TokenNameCOMMA
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
CHARSET_HEBREW	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
case	TokenNamecase
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
META_CHARSET_ARABIC	TokenNameIdentifier
:	TokenNameCOLON
return	TokenNamereturn
new	TokenNamenew
String	TokenNameIdentifier
(	TokenNameLPAREN
bstr	TokenNameIdentifier
,	TokenNameCOMMA
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
CHARSET_ARABIC	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
case	TokenNamecase
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
META_CHARSET_RUSSIAN	TokenNameIdentifier
:	TokenNameCOLON
return	TokenNamereturn
new	TokenNamenew
String	TokenNameIdentifier
(	TokenNameLPAREN
bstr	TokenNameIdentifier
,	TokenNameCOMMA
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
CHARSET_CYRILLIC	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
case	TokenNamecase
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
META_CHARSET_THAI	TokenNameIdentifier
:	TokenNameCOLON
return	TokenNamereturn
new	TokenNamenew
String	TokenNameIdentifier
(	TokenNameLPAREN
bstr	TokenNameIdentifier
,	TokenNameCOMMA
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
CHARSET_THAI	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
case	TokenNamecase
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
META_CHARSET_EASTEUROPE	TokenNameIdentifier
:	TokenNameCOLON
return	TokenNamereturn
new	TokenNamenew
String	TokenNameIdentifier
(	TokenNameLPAREN
bstr	TokenNameIdentifier
,	TokenNameCOMMA
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
CHARSET_EASTEUROPE	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
case	TokenNamecase
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
META_CHARSET_OEM	TokenNameIdentifier
:	TokenNameCOLON
return	TokenNamereturn
new	TokenNamenew
String	TokenNameIdentifier
(	TokenNameLPAREN
bstr	TokenNameIdentifier
,	TokenNameCOMMA
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
CHARSET_OEM	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
default	TokenNamedefault
:	TokenNameCOLON
}	TokenNameRBRACE
}	TokenNameRBRACE
catch	TokenNamecatch
(	TokenNameLPAREN
UnsupportedEncodingException	TokenNameIdentifier
e	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
}	TokenNameRBRACE
return	TokenNamereturn
new	TokenNamenew
String	TokenNameIdentifier
(	TokenNameLPAREN
bstr	TokenNameIdentifier
)	TokenNameRPAREN
;	TokenNameSEMICOLON
}	TokenNameRBRACE
public	TokenNamepublic
static	TokenNamestatic
int	TokenNameint
getHorizontalAlignment	TokenNameIdentifier
(	TokenNameLPAREN
int	TokenNameint
align	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
int	TokenNameint
v	TokenNameIdentifier
=	TokenNameEQUAL
align	TokenNameIdentifier
;	TokenNameSEMICOLON
v	TokenNameIdentifier
=	TokenNameEQUAL
v	TokenNameIdentifier
%	TokenNameREMAINDER
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
TA_BASELINE	TokenNameIdentifier
;	TokenNameSEMICOLON
v	TokenNameIdentifier
=	TokenNameEQUAL
v	TokenNameIdentifier
%	TokenNameREMAINDER
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
TA_BOTTOM	TokenNameIdentifier
;	TokenNameSEMICOLON
if	TokenNameif
(	TokenNameLPAREN
v	TokenNameIdentifier
>=	TokenNameGREATER_EQUAL
6	TokenNameIntegerLiteral
)	TokenNameRPAREN
return	TokenNamereturn
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
TA_CENTER	TokenNameIdentifier
;	TokenNameSEMICOLON
else	TokenNameelse
if	TokenNameif
(	TokenNameLPAREN
v	TokenNameIdentifier
>=	TokenNameGREATER_EQUAL
2	TokenNameIntegerLiteral
)	TokenNameRPAREN
return	TokenNamereturn
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
TA_RIGHT	TokenNameIdentifier
;	TokenNameSEMICOLON
else	TokenNameelse
return	TokenNamereturn
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
TA_LEFT	TokenNameIdentifier
;	TokenNameSEMICOLON
}	TokenNameRBRACE
public	TokenNamepublic
static	TokenNamestatic
int	TokenNameint
getVerticalAlignment	TokenNameIdentifier
(	TokenNameLPAREN
int	TokenNameint
align	TokenNameIdentifier
)	TokenNameRPAREN
{	TokenNameLBRACE
int	TokenNameint
v	TokenNameIdentifier
=	TokenNameEQUAL
align	TokenNameIdentifier
;	TokenNameSEMICOLON
if	TokenNameif
(	TokenNameLPAREN
(	TokenNameLPAREN
v	TokenNameIdentifier
/	TokenNameDIVIDE
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
TA_BASELINE	TokenNameIdentifier
)	TokenNameRPAREN
!=	TokenNameNOT_EQUAL
0	TokenNameIntegerLiteral
)	TokenNameRPAREN
return	TokenNamereturn
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
TA_BASELINE	TokenNameIdentifier
;	TokenNameSEMICOLON
v	TokenNameIdentifier
=	TokenNameEQUAL
v	TokenNameIdentifier
%	TokenNameREMAINDER
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
TA_BASELINE	TokenNameIdentifier
;	TokenNameSEMICOLON
if	TokenNameif
(	TokenNameLPAREN
(	TokenNameLPAREN
v	TokenNameIdentifier
/	TokenNameDIVIDE
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
TA_BOTTOM	TokenNameIdentifier
)	TokenNameRPAREN
!=	TokenNameNOT_EQUAL
0	TokenNameIntegerLiteral
)	TokenNameRPAREN
return	TokenNamereturn
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
TA_BOTTOM	TokenNameIdentifier
;	TokenNameSEMICOLON
else	TokenNameelse
return	TokenNamereturn
WMFConstants	TokenNameIdentifier
.	TokenNameDOT
TA_TOP	TokenNameIdentifier
;	TokenNameSEMICOLON
}	TokenNameRBRACE
}	TokenNameRBRACE
